/**
 * sanitizer.js - ZetaTavern XSS Prevention & Sanitization
 * Strictly filters HTML tags and attributes to prevent Cross-Site Scripting (XSS).
 */

/**
 * Escapes raw text to safe HTML characters.
 * @param {string} str 
 * @returns {string}
 */
export function escapeHTML(str) {
  if (!str) return '';
  return str.replace(/[&<>"']/g, match => {
    switch (match) {
      case '&': return '&amp;';
      case '<': return '&lt;';
      case '>': return '&gt;';
      case '"': return '&quot;';
      case "'": return '&#39;';
      default: return match;
    }
  });
}

/**
 * Sanitizes dirty HTML string, allowing only a strict whitelist of safe formatting tags.
 * Strips script tags, iframe, onerror/onload attributes, and javascript: links.
 * @param {string} dirtyHTML 
 * @returns {string}
 */
export function sanitizeHTML(dirtyHTML) {
  if (!dirtyHTML) return '';

  try {
    const parser = new DOMParser();
    const doc = parser.parseFromString(dirtyHTML, 'text/html');
    const body = doc.body;

    // Strict whitelist of allowed formatting tags
    const allowedTags = new Set([
      'H1', 'H2', 'H3', 'H4', 'H5', 'H6', 
      'P', 'BR', 'STRONG', 'EM', 'U', 'S', 
      'UL', 'OL', 'LI', 'SPAN', 'CODE', 'PRE', 
      'BLOCKQUOTE', 'TABLE', 'THEAD', 'TBODY', 'TR', 'TH', 'TD',
      'HR', 'A'
    ]);

    const cleanNode = node => {
      // Text node is always safe
      if (node.nodeType === Node.TEXT_NODE) {
        return node.cloneNode(true);
      }

      // If it's an element node
      if (node.nodeType === Node.ELEMENT_NODE) {
        const tagName = node.tagName;

        // If the tag is not in our whitelist, replace with its escaped text representation
        if (!allowedTags.has(tagName)) {
          return document.createTextNode(node.outerHTML);
        }

        const cleanEl = document.createElement(tagName);

        // Filter and sanitize attributes
        if (tagName === 'A') {
          const href = node.getAttribute('href');
          // Allow only http, https, relative, or anchor paths. Prevent javascript: protocol.
          if (href && (href.startsWith('http://') || href.startsWith('https://') || href.startsWith('#') || href.startsWith('./') || href.startsWith('../'))) {
            cleanEl.setAttribute('href', href);
            cleanEl.setAttribute('target', '_blank');
            cleanEl.setAttribute('rel', 'noopener noreferrer');
          }
        }

        // Keep code class names if generated by prism or markdown
        if (tagName === 'CODE' || tagName === 'SPAN') {
          const className = node.getAttribute('class');
          if (className && /^language-[\w-]+$/.test(className)) {
            cleanEl.setAttribute('class', className);
          }
        }

        // Recursively append clean child nodes
        for (const child of node.childNodes) {
          cleanEl.appendChild(cleanNode(child));
        }

        return cleanEl;
      }

      // Default fallback for comments, document fragments, etc.
      return document.createTextNode('');
    };

    const cleanFragment = document.createDocumentFragment();
    for (const child of body.childNodes) {
      cleanFragment.appendChild(cleanNode(child));
    }

    const container = document.createElement('div');
    container.appendChild(cleanFragment);
    return container.innerHTML;

  } catch (err) {
    console.error('HTML Sanitization failed, falling back to fully escaped content:', err);
    return escapeHTML(dirtyHTML);
  }
}
